id: "siamese"
env:
  result_dir: 'results'
  random_seed: 0
  stage1_epochs: 100
  stage2_epochs: 1000
  solver: 'siamese-solver'
  train_chunk_size: 50
  val_chunk_size: 1000
  test_chunk_size: 1000
  train_topk: 30
  val_topk: 20
  save_plain_models: True
  bipartite_threshold: 0.85
  update_stage2_negatives_frequency: 10
  second_stage_easy_epoch_number: 15
data:
  name: "MNIST"
  params:
    dataset_path: '/home/albert/data/MNIST'
    batch_size: 500
    eval_batch_size: 500
    input_size: [28, 28]
    input_channels: 1
    positive_rate: 0.5
    train_val_split: [0.8, 0.2]

    gpu_to_use: 0
    workers: 8
    load_into_memory: false

model:
  name: "HalfMNISTResNet"
  params:
    layers: [2, 2, 2, 2]
    input_channels: 1
    output_channels: 64
    pretrained: True

loss:
  name: 'WeightedL1Loss'
  params: {}

optimizer:
  name: 'Ranger'
  params:
    lr: 0.0001
    weight_decay: 0.0001

lr_policy:
  name: 'ReduceLROnPlateau'
  params:
    mode: 'max'
    patience: 5